accelerator: null
accumulate_grad_batches: null
adam_epsilon: 0.001
amp_backend: native
amp_level: null
auto_lr_find: ''
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
data_dirpath: prepared
data_filename_prefix: task2_
data_filename_type: tsv
data_split_test: test
data_split_train: train
data_split_valid: valid
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
encoder_learning_rate: 1.0e-05
eval_batch_size: 32
eval_splits: null
fast_dev_run: false
fields_transformations: ''
flush_logs_every_n_steps: null
gpus: 0
gradient_clip_algorithm: null
gradient_clip_val: null
ipus: null
learning_rate: 1.0e-05
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
loader_workers: 8
log_every_n_steps: 50
log_gpu_memory: null
logger: true
logs_path: tracking/tensorboard_logs
max_epochs: 1
max_seq_length: 160
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_name_or_path: distilbert-base-uncased
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_extra_features: 0
num_labels: 3
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
patience: 3
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
resume_from_ckpt: ''
stochastic_weight_avg: false
strategy: null
stratified_batch_sampling: true
sync_batchnorm: false
t10sec: 1
task_name: base
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
train_batch_size: 32
train_data_size: 100
use_weights_of: ''
val_check_interval: 1.0
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
